# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8a4ef4fe79f9d5c5c16d0fa9cfe91d63602819e84c79372f10eaf66272d4c49579a587a7d52c385f26725eacefef8900509f3e102fece4cda67381692ecc114

test:
  secret_key_base: 1a48af264e22ee2d692187dac16d94c19b2472230e6954e5369d844b6edc55b6fc3e48eaeb1b37ab2a9ffc509c445fa972983153b2ae105d7cb836661a75e0ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
